/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaInterface;

import CapaNegocio.ClsBdEstudiante;
import CapaNegocio.ClsEstudiante;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class WinEstudiante extends javax.swing.JFrame {
    ClsBdEstudiante Estudiantes,Notas;
    ClsEstudiante promedio, estado, respuesta;
    int clv;
    float notas;
    /**
     * Creates new form WinEstudiante
     */
    public WinEstudiante() {
        initComponents();
        
        ArchBd.setVisible(false);
        PnlDatos_Estudiante.setVisible(false);
        PnlAcerca_de.setVisible(false);
        PnlResultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlDatos_Estudiante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CmbNotas = new javax.swing.JComboBox<>();
        BtnSiguiente = new javax.swing.JButton();
        BtnAnterior = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PnlResultado = new javax.swing.JPanel();
        txtResultado = new javax.swing.JTextField();
        BtnResultado = new javax.swing.JButton();
        ArchBd = new javax.swing.JFileChooser();
        PnlAcerca_de = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnRetornar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuConexion = new javax.swing.JMenu();
        MnuAbrir = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MnuEstudiantes = new javax.swing.JMenu();
        MnuIndividual = new javax.swing.JMenuItem();
        MnuMateria = new javax.swing.JMenuItem();
        MnuEstudiante = new javax.swing.JMenu();
        MnuAcerca_de = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evaluacion Final de: Freddy Alejandro Calahorrano Rivera");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnlDatos_Estudiante.setToolTipText("Datos del Estudiante");

        jLabel1.setText("Clave: ");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Direccion: ");

        jLabel4.setText("Sexo: ");

        jLabel5.setText("Notas: ");

        CmbNotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });

        BtnAnterior.setText("Anterior");
        BtnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnteriorActionPerformed(evt);
            }
        });

        jButton3.setText("Retornar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlResultadoLayout = new javax.swing.GroupLayout(PnlResultado);
        PnlResultado.setLayout(PnlResultadoLayout);
        PnlResultadoLayout.setHorizontalGroup(
            PnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
        PnlResultadoLayout.setVerticalGroup(
            PnlResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlResultadoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        BtnResultado.setText("Resultado del Estudiante");
        BtnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlDatos_EstudianteLayout = new javax.swing.GroupLayout(PnlDatos_Estudiante);
        PnlDatos_Estudiante.setLayout(PnlDatos_EstudianteLayout);
        PnlDatos_EstudianteLayout.setHorizontalGroup(
            PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatos_EstudianteLayout.createSequentialGroup()
                .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlDatos_EstudianteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlDatos_EstudianteLayout.createSequentialGroup()
                                .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombre)
                                        .addComponent(txtDireccion)
                                        .addComponent(txtSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                                    .addComponent(CmbNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addGroup(PnlDatos_EstudianteLayout.createSequentialGroup()
                                .addComponent(BtnSiguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3))))
                    .addGroup(PnlDatos_EstudianteLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(BtnResultado))
                    .addGroup(PnlDatos_EstudianteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(PnlResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        PnlDatos_EstudianteLayout.setVerticalGroup(
            PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlDatos_EstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PnlDatos_EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSiguiente)
                    .addComponent(BtnAnterior)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(BtnResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PnlDatos_Estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 510));

        ArchBd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchBdActionPerformed(evt);
            }
        });
        getContentPane().add(ArchBd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel6.setText("Autor: Freddy Calahorrano");

        jLabel7.setText("Tipo: Examen del Segundo parcial Programacion Orientada a Objetos.");

        jLabel8.setText("Vercion 1.0");

        jLabel9.setText("Copyring 2019 - 2020");

        jLabel10.setText("Todos los derechos de Autos estan Reservados.");

        BtnRetornar.setText("Retornar");
        BtnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlAcerca_deLayout = new javax.swing.GroupLayout(PnlAcerca_de);
        PnlAcerca_de.setLayout(PnlAcerca_deLayout);
        PnlAcerca_deLayout.setHorizontalGroup(
            PnlAcerca_deLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAcerca_deLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAcerca_deLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(PnlAcerca_deLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BtnRetornar)
                        .addComponent(jLabel10)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        PnlAcerca_deLayout.setVerticalGroup(
            PnlAcerca_deLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAcerca_deLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(BtnRetornar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PnlAcerca_de, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MnuConexion.setText("Conexion");

        MnuAbrir.setText("Abrir");
        MnuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAbrirActionPerformed(evt);
            }
        });
        MnuConexion.add(MnuAbrir);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MnuConexion.add(jMenuItem2);

        jMenuBar1.add(MnuConexion);

        MnuEstudiantes.setText("Estudiantes");

        MnuIndividual.setText("Individual");
        MnuIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuIndividualActionPerformed(evt);
            }
        });
        MnuEstudiantes.add(MnuIndividual);

        MnuMateria.setText("Materia");
        MnuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuMateriaActionPerformed(evt);
            }
        });
        MnuEstudiantes.add(MnuMateria);

        jMenuBar1.add(MnuEstudiantes);

        MnuEstudiante.setText("Ayuda");

        MnuAcerca_de.setText("Acerca de");
        MnuAcerca_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuAcerca_deActionPerformed(evt);
            }
        });
        MnuEstudiante.add(MnuAcerca_de);

        jMenuBar1.add(MnuEstudiante);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAbrirActionPerformed
        ArchBd.setVisible(true);
    }//GEN-LAST:event_MnuAbrirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MnuIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuIndividualActionPerformed
        ArchBd.setVisible(false);
        PnlDatos_Estudiante.setVisible(true);
    }//GEN-LAST:event_MnuIndividualActionPerformed

    private void MnuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuMateriaActionPerformed
        ArchBd.setVisible(false);
        PnlDatos_Estudiante.setVisible(false);
        PnlResultado.setVisible(true);
    }//GEN-LAST:event_MnuMateriaActionPerformed

    private void MnuAcerca_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAcerca_deActionPerformed
        ArchBd.setVisible(false);
        PnlDatos_Estudiante.setVisible(false);
        PnlAcerca_de.setVisible(true);
    }//GEN-LAST:event_MnuAcerca_deActionPerformed

    private void ArchBdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchBdActionPerformed
        File f = ArchBd.getSelectedFile();
        String BaseDatos= f.getAbsolutePath();
        try
        {
            Estudiantes =new ClsBdEstudiante(BaseDatos);
            Estudiantes.consulta("TbEstudiante");
            Notas =new ClsBdEstudiante(BaseDatos);
            Notas.consulta("TbNotas");
        }
        catch (SQLException ex)
        {
            Logger.getLogger(WinEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArchBd.setVisible(false);
    }//GEN-LAST:event_ArchBdActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        try 
            {
                Estudiantes.siguiente();
                {
                    
                    txtClave.setText(Estudiantes.registros().getString("Clavest"));
                    txtNombre.setText(Estudiantes.registros().getString("Nombre"));
                    txtDireccion.setText(Estudiantes.registros().getString("Direccion"));
                    txtSexo.setText(Estudiantes.registros().getString("Sexo"));
                    clv=Estudiantes.registros().getInt("Clavest");
                    Notas.consultanota(clv);
                    CmbNotas.removeAllItems();
                    for(int i=0; Notas.registros().next() ; i++)
                    {
                        CmbNotas.addItem(Notas.registros().getString("Nota"));
                    }
                    Notas.registros().close();
                }   
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(WinEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void BtnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnteriorActionPerformed
        try 
            {
                Estudiantes.anterior();
                {
                    txtClave.setText(Estudiantes.registros().getString("Clavest"));
                    txtNombre.setText(Estudiantes.registros().getString("Nombre"));
                    txtDireccion.setText(Estudiantes.registros().getString("Direccion"));
                    txtSexo.setText(Estudiantes.registros().getString("Sexo"));
                    clv=Estudiantes.registros().getInt("Clavest");
                    Notas.consultanota(clv);
                    CmbNotas.removeAllItems();
                    for(int i=0; Notas.registros().next() ; i++)
                    {
                        CmbNotas.addItem(Notas.registros().getString("Nota"));
                    }
                    Notas.registros().close();
                }   
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(WinEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_BtnAnteriorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtClave.setText(null);
        txtNombre.setText(null);
        txtDireccion.setText(null);
        txtSexo.setText(null);
        PnlDatos_Estudiante.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetornarActionPerformed
        PnlAcerca_de.setVisible(false);
    }//GEN-LAST:event_BtnRetornarActionPerformed

    private void BtnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResultadoActionPerformed
        PnlResultado.setVisible(true);
        int contador=0;
        try 
            {
                Estudiantes.registros();
                clv=Estudiantes.registros().getInt("Clavest");
                Notas.consultanota(clv);
                    for(int i=0; Notas.registros().next() ; i++)
                    {
                        float notas_base=Float.parseFloat(Notas.registros().getString("Nota"));
                        notas=notas+notas_base;
                        contador=contador+1;
                    }
                    
                    String nombre = Estudiantes.registros().getString("Nombre");
                    promedio= new ClsEstudiante();
                    float prom = promedio.promedio(notas,contador);
                    estado= new ClsEstudiante();
                    boolean est = estado.estado(prom);
                    respuesta= new ClsEstudiante();
                    String res = respuesta.toString(nombre, prom, est);
                    Notas.registros().close();
                  txtResultado.setText(res);
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(WinEstudiante.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_BtnResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ArchBd;
    private javax.swing.JButton BtnAnterior;
    private javax.swing.JButton BtnResultado;
    private javax.swing.JButton BtnRetornar;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JComboBox<String> CmbNotas;
    private javax.swing.JMenuItem MnuAbrir;
    private javax.swing.JMenuItem MnuAcerca_de;
    private javax.swing.JMenu MnuConexion;
    private javax.swing.JMenu MnuEstudiante;
    private javax.swing.JMenu MnuEstudiantes;
    private javax.swing.JMenuItem MnuIndividual;
    private javax.swing.JMenuItem MnuMateria;
    private javax.swing.JPanel PnlAcerca_de;
    private javax.swing.JPanel PnlDatos_Estudiante;
    private javax.swing.JPanel PnlResultado;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtSexo;
    // End of variables declaration//GEN-END:variables
}
